services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080" 
    env_file:
      - .env
    restart: always
  
  frontend:
    build:
      context: ./web
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ./web/.env
    environment:
      - BACKEND_URL=http://backend:8080  # Changed from localhost to service name
    depends_on:
      - backend
    restart: always
